// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissionSix.Models;

namespace MissionSix.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    [Migration("20230213221635_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("MissionSix.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Drama",
                            Director = "Joe Wright",
                            Edited = true,
                            Rating = "PG-13",
                            Title = "Pride and Prejudice",
                            Year = 2005
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "television",
                            Director = "Fox",
                            Edited = true,
                            Rating = "PG-13",
                            Title = "New Girl",
                            Year = 2011
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Family",
                            Director = "John Lasseter",
                            Edited = true,
                            Rating = "PG",
                            Title = "Toy Story",
                            Year = 1995
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
